[package]
name = "moonwave-extractor"
version = "0.1.0"
authors = ["eryn L. K. <eryn@eryn.io>"]
edition = "2018"

[lib]
name = "libmoonwave"
path = "src/lib.rs"

[[bin]]
name = "moonwave-extractor"
path = "src/main.rs"

[profile.dev]
opt-level = 1

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
full_moon = { git = "https://github.com/Kampfkarren/full-moon", rev = "592dcda974d00fad0bd4065b9376375bcf516393" }
walkdir = "2"
anyhow = "1.0.28"
codespan-reporting = "0.9.5"
structopt = "0.3.18"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.58"
pathdiff = "0.2.0"

[dev-dependencies]
insta = "1.1.0"